#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Pre Commit Tests: Linting + Type Checking 🏗️👷'

# Check Prettier standards
# npm run check-format ||
# (
#     echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
#             Prettier Check Failed. Run npm run format, add changes and try commit again.';
#     false;
# )

# Check ESLint Standards
npm run check-lint ||
(
        echo '🏀👋😬 ESLint Check Failed!  
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

echo '✅ Linting passed successfully.'
# Check tsconfig standards
npm run check-types ||
(
    echo '🥲🙃🥴 Failed Type check.'
    false;
)

echo '✅ Type Chceking passed successfully.'
# If everything passes... Now we can commit

# echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'
# npm run build ||
# (
#     echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
#             Next build failed: View the errors above to see why. 
#     '
#     false;
# )

# If everything passes... Now we can commit